name: '🚀 Push Test'

on:
  push:
    branches:
      - main

jobs:
  test_deprecation_action:
    name: '🔬 Test Deprecation Action'
    runs-on: ubuntu-latest
    steps:
      - name: '🛒 Checkout code'
        uses: actions/checkout@v3

      - name: '🚀 Run Deprecated Action'
        uses: ./ # Uses the action in the root directory
        with:
          start-date: '2025-07-01'
          days-till-error: '10'
          warning-message: |
            ### :warning: Deprecation Warning
            This is a test warning message.
            Please check the [documentation](https://github.com/actions/checkout).
          error-message: |
            ### :x: Deprecation Error
            This is a test error message.
            Please check the [documentation](https://github.com/actions/checkout).
